include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root/index.php;
fastcgi_param SCRIPT_NAME /index.php;
fastcgi_param HTTP_PROXY "";
fastcgi_pass unix:/run/php/__APP_USER__.sock;
fastcgi_read_timeout 900s;
fastcgi_send_timeout 900s;
fastcgi_hide_header X-Powered-By;
