#!/usr/bin/env bash
# Installs a release tarball built by deploy/deploy.mjs into /home/<app user>/app.
# Runs as root on the VPS. Keeps config/ and var/ across releases.
#
#   install-release.sh --release /tmp/x/release.tgz [--app-user hermesweb] [--hermes-home /home/hermes]
#                      [--domain ui.example.com] [--app-name "Hermes"] [--default-lang en]
#
# --domain is required on the first install: it generates config/config.php and copies
# API_SERVER_KEY from the Hermes .env (root is the only user allowed to read both sides).
set -euo pipefail

RELEASE=""
APP_USER="hermesweb"
HERMES_HOME="/home/hermes"
DOMAIN=""
APP_NAME="Hermes"
DEFAULT_LANG="en"

while [ $# -gt 0 ]; do
  case "$1" in
    --release)      RELEASE="$2"; shift 2 ;;
    --app-user)     APP_USER="$2"; shift 2 ;;
    --hermes-home)  HERMES_HOME="$2"; shift 2 ;;
    --domain)       DOMAIN="$2"; shift 2 ;;
    --app-name)     APP_NAME="$2"; shift 2 ;;
    --default-lang) DEFAULT_LANG="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

fail() { echo "ERROR: $*" >&2; exit 1; }
[ "$(id -u)" -eq 0 ] || fail "run as root"
[ -f "$RELEASE" ] || fail "--release file not found"
APP_ROOT="/home/$APP_USER/app"
[ -d "$APP_ROOT/var" ] || fail "$APP_ROOT not provisioned; run provision.sh first"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
tar -xzf "$RELEASE" -C "$STAGE"
for d in bin src public; do
  [ -d "$STAGE/$d" ] || fail "release is missing $d/"
done
[ -f "$STAGE/public/assets/.vite/manifest.json" ] || fail "release has no built frontend"

echo "== code"
for d in bin src public; do
  rm -rf "$APP_ROOT/$d.old"
  [ -e "$APP_ROOT/$d" ] && mv "$APP_ROOT/$d" "$APP_ROOT/$d.old"
  mv "$STAGE/$d" "$APP_ROOT/$d"
done
install -m 600 "$STAGE/config/config.example.php" "$APP_ROOT/config/config.example.php"

echo "== config"
if [ ! -f "$APP_ROOT/config/config.php" ]; then
  [[ "$DOMAIN" =~ ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$ ]] || fail "--domain is required on the first install"
  [[ "$DEFAULT_LANG" =~ ^(en|de)$ ]] || fail "--default-lang must be en or de"
  ENV_FILE="$HERMES_HOME/.hermes/.env"
  [ -f "$ENV_FILE" ] || fail "$ENV_FILE not found"
  KEY="$(grep -m1 '^API_SERVER_KEY=' "$ENV_FILE" | cut -d= -f2- | tr -d "\r\"' ")"
  PORT="$(grep -m1 '^API_SERVER_PORT=' "$ENV_FILE" | cut -d= -f2- | tr -d "\r\"' ")"
  [ -n "$KEY" ] || fail "API_SERVER_KEY not set in $ENV_FILE"
  (
    umask 077
    KOCO_KEY="$KEY" KOCO_SECRET="$(openssl rand -hex 32)" KOCO_URL="https://$DOMAIN" \
    KOCO_PORT="${PORT:-8642}" KOCO_NAME="$APP_NAME" KOCO_LANG="$DEFAULT_LANG" \
    php -r '
      require $argv[3];
      $c = require $argv[1];
      $c["app_name"] = getenv("KOCO_NAME");
      $c["base_url"] = getenv("KOCO_URL");
      $c["default_lang"] = getenv("KOCO_LANG");
      $c["hermes"]["base_url"] = "http://127.0.0.1:" . getenv("KOCO_PORT");
      $c["hermes"]["api_key"] = getenv("KOCO_KEY");
      $c["security"]["secret"] = getenv("KOCO_SECRET");
      $vapid = KocoUI\Push\Vapid::generate();
      $c["push"]["vapid_subject"] = "mailto:admin@" . parse_url(getenv("KOCO_URL"), PHP_URL_HOST);
      $c["push"]["vapid_public"] = $vapid["public"];
      $c["push"]["vapid_private"] = $vapid["private"];
      file_put_contents($argv[2], "<?php\n// generated by install-release.sh\nreturn " . var_export($c, true) . ";\n");
    ' "$APP_ROOT/config/config.example.php" "$APP_ROOT/config/config.php" "$APP_ROOT/src/autoload.php"
  )
  unset KEY
  echo "generated config.php for https://$DOMAIN"
else
  echo "config.php exists, unchanged"
  # Fill Web Push keys if an older config lacks them (does not rotate existing keys).
  php -r '
    require $argv[1];
    $file = $argv[2];
    $c = require $file;
    if (!is_array($c)) exit(0);
    $pub = (string)($c["push"]["vapid_public"] ?? "");
    $priv = (string)($c["push"]["vapid_private"] ?? "");
    if ($pub !== "" && $priv !== "") { echo "push VAPID already set\n"; exit(0); }
    $vapid = KocoUI\Push\Vapid::generate();
    $host = parse_url((string)($c["base_url"] ?? ""), PHP_URL_HOST) ?: "example.com";
    $c["push"] = [
      "vapid_subject" => (string)($c["push"]["vapid_subject"] ?? "mailto:admin@$host"),
      "vapid_public" => $vapid["public"],
      "vapid_private" => $vapid["private"],
    ];
    file_put_contents($file, "<?php\n// updated by install-release.sh (push VAPID)\nreturn " . var_export($c, true) . ";\n");
    echo "added push VAPID keys to config.php\n";
  ' "$APP_ROOT/src/autoload.php" "$APP_ROOT/config/config.php" || true
fi

echo "== permissions"
chown -R "$APP_USER:$APP_USER" "$APP_ROOT"
# code: app user only; public/: readable by nginx (www-data is in the app user's group)
find "$APP_ROOT/bin" "$APP_ROOT/src" -type d -exec chmod 700 {} +
find "$APP_ROOT/bin" "$APP_ROOT/src" -type f -exec chmod 600 {} +
find "$APP_ROOT/public" -type d -exec chmod 750 {} +
find "$APP_ROOT/public" -type f -exec chmod 640 {} +
chmod 700 "$APP_ROOT/config" "$APP_ROOT/var"
chmod 600 "$APP_ROOT/config/"*.php
find "$APP_ROOT/var/data" -type f -exec chmod 600 {} +

echo "== check"
runuser -u "$APP_USER" -- php "$APP_ROOT/bin/kocoui" check || fail "post-install check failed (old code kept in *.old)"

PHPV="$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')"
systemctl reload "php$PHPV-fpm"
rm -rf "$APP_ROOT/bin.old" "$APP_ROOT/src.old" "$APP_ROOT/public.old"
echo "== installed"
